{% set name = "keras-mdn-layer" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keras-mdn-layer-{{ version }}.tar.gz
  sha256: a4b5a015df8f47e558ff4b5cc7304e810207c3194b7a04cb5f4800a6ad01a204

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - mdn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cpmpercussion/keras-mdn-layer
  summary: An MDN Layer for Keras using TensorFlow Probability.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
